common:
  user:
    form_signup:
      size: "25"
    form_login:
      size: "30"
controller:
  admin:
    categories:
      per_page: 10
  products:
    per_page: 10
user:
  size: 80
  name:
    length:
      maximum: 50
  email:
    length:
      maximum: 255
  password:
    length:
      minimum: 6
